gfm:
  ext:  'md'
  name: 'Github Flavored Markdown' 
wp:
  ext:  'wp'
  name: 'WordPress Flavored Readme'
markdown:
  ext:  'md'
  name: 'Simple Markdown'
rdoc:
  ext:  'rdoc'
  name: 'RDoc'
textile:
  ext:  'textile'
  name: 'Textile'
mediawiki:
  ext:  'wiki'
  name: 'MediaWiki'
org:
  ext:  'org'
  name: 'Org'
creole:
  ext:  'creole'
  name: 'Creole'